/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2022-09-14 01:06:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jquery13;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"EUC-KR\">\r\n");
      out.write("\t\t<title>jquery 연습</title>\r\n");
      out.write("\t\t<script src=\"jquery-3.6.0.js\"></script>\r\n");
      out.write("\t</head>\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar checkID = false;\r\n");
      out.write("\t\t//00:아이디 검사 안함\r\n");
      out.write("\t\t//01:아이디가 중복됨\r\n");
      out.write("\t\t//02:회원 가입 가능한 아이디\r\n");
      out.write("\t\tvar CheckState =\"00\";\r\n");
      out.write("\t\twindow.onload = function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//키보드 이벤트 종류 : keypress, keyup, keydown\r\n");
      out.write("\t\t\t$(\"#id\").keyup(\r\n");
      out.write("\t\t\t\tfunction()\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar UserID = $(\"#id\").val();\r\n");
      out.write("\t\t\t\t\t//$(\"#spanMsg\").html($(\"#id\").val());\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\t\t\t\turl: \"idcheck.jsp?id=\" + UserID,\r\n");
      out.write("\t\t\t\t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t//xml을 이용한 아이디 중복검사\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tCheckState = $(data).find(\"code\").text();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#spanMsg\").html($(data).find(\"msg\").text());\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t// 통신이 성공적으로 이루어졌을때 이 함수를 타게 된다.\r\n");
      out.write("\t\t\t\t\t\t\t//data = data.trim();   //html로 넘어온 값의 공백을 업애줌\r\n");
      out.write("\t\t\t\t\t\t\t//alert(\"[\" + data + \"]\"); // 공백 확인용\r\n");
      out.write("\t\t\t\t\t\t\t//ary = data.split(\":\"); //콜론 단위로 문자열을 잘라줌\r\n");
      out.write("\t\t\t\t\t\t\t//code = ary[0];       \r\n");
      out.write("\t\t\t\t\t\t\t//msg = ary[1];\r\n");
      out.write("\t\t\t\t\t\t\t//CheckState = code;\r\n");
      out.write("\t\t\t\t\t\t\t//$(\"#spanMsg\").html(msg);\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function(xhr, status, error)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t// 통신 오류 발생시\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#spanMsg\").html(\"검사 오류입니다.\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction CheckSubmit()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar userID = $(\"#id\").val();\r\n");
      out.write("\t\t\tif( userID == \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif( CheckState == \"00\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t//00:아이디 검사 안함\r\n");
      out.write("\t\t\t\talert(\"아이디 중복 검사가 수행되지 않았습니다.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif( CheckState == \"01\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t//01:아이디가 중복됨\r\n");
      out.write("\t\t\t\talert(\"중복 된 아이디 입니다.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<form name=\"join\" method=\"post\" action=\"joinok.jsp\" onsubmit=\"return CheckSubmit();\">\r\n");
      out.write("\t\t<table border=\"0\" style=\"width:700px; \" align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"height:40px\">\r\n");
      out.write("\t\t\t\t\t<span style=\"font-weight:bold; color:red;\">※ 회원가입</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table border=\"1\" style=\"width:700px; \" align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width:130px;\">아이디 (*)</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"id\" name=\"id\" size=\"20\">\r\n");
      out.write("\t\t\t\t<span id=\"spanMsg\" name=\"spanMsg\" style=\"width:200px\">아이디를 입력하세요.</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>비밀번호 (*)</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"pw\"  style=\"width:95%\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>비밀번호 확인 (*)</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"pwcheck\" style=\"width:95%\"></td>\r\n");
      out.write("\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>이름 (*)</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"name\"  style=\"width:95%\"></td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>성별 (*)</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" value=\"M\" name=\"gender\" checked>남자\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" value=\"F\" name=\"gender\">여자\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>취미 (*)</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"hobby\" >\r\n");
      out.write("\t\t\t\t\t\t<option value=\"001\" selected>낚시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"002\">여행</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"003\">게임</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>관심분야</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" value=\"001:책\" name=\"interest\"  checked>책\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" value=\"002:영화\" name=\"interest\">영화\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" value=\"003:유튜브\" name=\"interest\">유튜브\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" value=\"004:낚시\" name=\"interest\">낚시\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"가입완료\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"취소\">\r\n");
      out.write("\t\t\t\t</td>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
